---
title: "behavior_sanity check_srndnaUGR"
author: "Jen Yang"
date: "2025-04-09, last modified 2025-04-09"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    hightlight: zenburn
    toc_depth: 6
---

```{r clean, include=FALSE}
# clean environment
rm(list = ls())
```

# Load libraries
```{r libraries, message_bi=FALSE, warning=TRUE, include=FALSE}
library(car)
library(plyr)
library(foreign)
library(pscl)
library(boot)
library(MASS)
library(robust)
library(sfsmisc)
library(ggplot2)
library(reshape2)
library(ppcor)
library(ggrepel)
library(Hmisc)
library(tidyverse)
library(sandwich)
library(ggpubr)
library(interactions)
library(knitr)
library(twowaytests)
library(ggfortify)
library(interactions)
library(broom)
library(patchwork)
library(robustbase)
library(lmtest)
library(modelr)
library(Rmisc)
# library(raincloudplots)
library(cowplot)
library(readr)
library(PupillometryR)
library(ggpp)
library(estimatr)
library(skedastic)
library(ggpubr)
library(lubridate)
library(readxl)
library(gridExtra)
library(scales)
library(rstudioapi)
library(jsonlite)
library(rjson)
library(readr)
library(hBayesDM)
library(brms)
library(emmeans)
library(mediation)
library(here)
library(lme4)
library(broom.mixed)
library(easyRT)
library(parameters)
library(effectsize)
library(effects)
library(lmerTest)
library(ez)
library(afex)
library(marginaleffects)
```

```{r}
set.seed(123)
```
purpose: to check if there's abnormal behaviors in participants such as accepting more unfair offers than fair offers

conclusion: all look good

# define directory
```{r}
gitrepo_path = "/Users/momocco/Documents/GitHub/srndna-ug/behavioral_analyses"

data_dir = paste(gitrepo_path,"data", sep = "/")
codes_dir = paste(gitrepo_path, "codes", sep = "/")
fit_dir = paste(gitrepo_path,"fits", sep = "/")
figure_dir = paste(gitrepo_path,"figures", sep = "/")
```

# load and prepare data
```{r}
# load subs
all_trials_df = read.csv(paste(data_dir, "all_trials_brains.csv", sep = "/"), header = TRUE) %>% 
  .[.$missed == 0,]

colnames(all_trials_df)[colnames(all_trials_df) == "subjID"] <- "participant_id"
indiv_df = read.csv(paste(data_dir, "participant_check.csv", sep = "/"), header = TRUE)  %>%
  mutate(age_bi = case_when(age <= 36 ~ "younger",
                            age > 36 ~ "older"))

all_trials_df = merge(all_trials_df, indiv_df, by.x = "participant_id", by.y = "participant_id")

sublist_final = read.csv(paste(data_dir, "participant_L3_47.csv", sep = "/"), header = TRUE)

all_trials_df = all_trials_df[all_trials_df$participant_id %in% sublist_final$subjID,]

## add a categorical variable that differentiate three groups
all_trials_df = all_trials_df %>% 
  mutate(group_tri = as.factor(case_when(human == 0 ~ 0, # computer
                               human == 1 & ingroup == 0 ~ 1, # outgroup
                               human == 1 & ingroup == 1 ~ 2))) # ingroup
# all_trials_df$group_tri = relevel(all_trials_df$group_tri, ref = "0") # computer

all_trials_df = all_trials_df %>% mutate(human = as.factor(human))

all_trials_df$group_tri = relevel(all_trials_df$group_tri, ref = "1") # outgroup

all_trials_df$age_bi = relevel(as.factor(all_trials_df$age_bi), ref = "younger")

all_trials_df = all_trials_df %>% 
  mutate(age_bi_dummy = case_when(age_bi == "younger" ~ 0,
                                  age_bi == "older" ~ 1)
         )

sub_list = unique(all_trials_df$participant_id)
```

# rejection rate per offer per sub
```{r}
## check unique offer
offer_list = unique(sort(all_trials_df$offer, decreasing = FALSE))

## prepare empty df
offer_accept_cols = c("subID", "offer", "accept_rate", "age_old")
offer_accept_df = data.frame(matrix(nrow = length(sub_list) * length(offer_list), 
                                    ncol = length(offer_accept_cols)))
colnames(offer_accept_df) = offer_accept_cols

for (sub_s in 1:length(sub_list)) {
  # sub_s = 2
  subID_s = sub_list[sub_s]
  s_age = sublist_final[sublist_final$subjID == subID_s ,"older"]
  df_s = all_trials_df[all_trials_df$participant_id == subID_s,] %>% 
    select(offer, accept)
  for (offer_i in 1:length(offer_list)) {
    # offer_i = 1
    offer_size_i = offer_list[offer_i]
    # offer_size_i
    accept_rate_i = sum(df_s$offer == offer_size_i & df_s$accept == 1)/sum(df_s$offer == offer_size_i)
    # accept_rate_i
    offer_accept_df[(sub_s-1)*length(offer_list) + offer_i, "subID"] = subID_s
    offer_accept_df[(sub_s-1)*length(offer_list) + offer_i, "offer"] = offer_size_i
    offer_accept_df[(sub_s-1)*length(offer_list) + offer_i, "accept_rate"] = accept_rate_i
    offer_accept_df[(sub_s-1)*length(offer_list) + offer_i, "age_old"] = s_age
  }
}
offer_accept_df$age_old = as.factor(offer_accept_df$age_old)
```


```{r}
axis_title = 16
axis_ticks = 10
axis_text = 12
axis_label = 14
legend_all = 12
alpha_level = 0.8

w = 5
h = 4

p_line =
  ggplot(offer_accept_df, aes(x = offer, y = accept_rate, color = age_old, group = subID)) +
  # theme(legend.position = "none") +
  labs(x = "offer size in $", y = "% accept", color = "age group") +
  geom_smooth(formula = "y~x",
              method = "lm",
              se = FALSE,
              linetype = "solid",
              linewidth = 1) +
  # geom_line(linetype = "solid",
  #             linewidth = 1,
  #           alpha = 0.2) +
  coord_cartesian(xlim=c(1, 10), ylim = c(0,1)) +
  scale_color_discrete(limits = c("0","1"), labels = c("18-35", "65-80")) +
  # ylim(0,1) + xlim(1,10) +
  theme(axis.line = element_line(linewidth = 1, colour = "black", linetype=1),
        axis.text.x = element_text(size = axis_text), 
        axis.text.y = element_text(size = axis_text), 
        axis.title.x = element_text(size = axis_title, face="bold"), 
        axis.title.y = element_text(size = axis_title, face="bold"))

ggsave(paste(figure_dir, "behavior_sanity_check.png", sep = "/"), 
       p_line, width = w*1.5, height = h)
```

